### ISSUE TITLE
Fatal error on plugin activation

### ISSUE THREAD

**Issue by bigorno** [TweetPressFr/jm-twitter-cards#68] opened 2016-11-11 17:28 UTC
hi guys

just to make you know that we face an issue trying to activate JM Twitter Cards. The problem happe with wordpress setted in french language. Trying to activate the plugin we got a fatal error

we resolved setting wordpress in english, activating the plugin and then coming back to the french. 

Probably a missing quote in the french language file

**Comment by TweetPressFr** [comment] 2016-11-14 20:31
I'm to look into it quickly quickly

**Comment by bigorno** [comment] 2016-11-14 20:49
Perfect thank you very much

*Walid Gabteni*
Via Carlo Cattaneo, 12
50019 Florence - Italie
Tel : +39 334 248 88 59
*Skype - walid.gabteni*
Twitter - @LightOnSEO <https://twitter.com/lightonseo>
Site - http://www.lightonseo.com

2016-11-14 21:31 GMT+01:00 Julien Maury <notifications@github.com>:

**Comment by TweetPressFr** [comment] 2016-11-23 13:56
Hi there, sorry no time until now. I cannot reproduce this bug. I've set my installation in French and the plugin activates. Would be nice if you find any hint there https://github.com/TweetPressFr/jm-twitter-cards/blob/master/languages/jm-tc-fr_FR.po, where's the missing quote for you ?

**Comment by TweetPressFr** [comment] 2017-03-25 18:08
should be fixed now, otherwise please open another issue, can't do more on this one.

**Closed by TweetPressFr** 2017-03-25 18:08 UTC
